// import 'jquery'
// import './shared/libs/libs/fancybox/jquery.fancybox.min.js'
// import './shared/libs/libs/owl-carousel/owl.carousel.js'
// import './shared/libs/libs/slick/slick.js'
// import './shared/libs/scripts/header-global.js'
// import './shared/libs/scripts/header-global-mobile.js'
// import './shared/libs/scripts/header-search-catalog.js'
// import './shared/libs/scripts/header-search-catalog-mobile.js'
// import './shared/libs/scripts/scripts.js'
// import './shared/libs/scripts/new.js'
// import './shared/libs/scripts/frontpage.js'

import './app/index.js'
